In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r"C:\Users\abc\OneDrive\Desktop\Data Science\projects\loan approval prediction\Data\loan_approval.csv")

In [3]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2000 non-null   str
 1   city            2000 non-null   str
 2   income          2000 non-null   int64
 3   credit_score    2000 non-null   int64
 4   loan_amount     2000 non-null   int64
 5   years_employed  2000 non-null   int64
 6   points          2000 non-null   float64
 7   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4), str(2)
memory usage: 111.5 KB

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.isnull().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df['name']
df[['name']]

                 name
0        Allison Hill
1        Brandon Hall
2        Rhonda Smith
3     Gabrielle Davis
4        Valerie Gray
...               ...
1995   James Schaefer
1996        Diana Lin
1997    Brandon Meyer
1998      Jason Price
1999     Nicole Brown

[2000 rows x 1 columns]

In [9]:
df['name'].unique()  # give unique values in brand column

<StringArray>
[        'Allison Hill',         'Brandon Hall',         'Rhonda Smith',
      'Gabrielle Davis',         'Valerie Gray',       'Darren Roberts',
           'Holly Wood',      'Nicholas Martin',          'Patty Perez',
           'Emily Rios',
 ...
       'Rebecca Newman', 'Christopher Morrison',        'Sierra Gentry',
        'Hannah Carter',          'Ryan Thomas',       'James Schaefer',
            'Diana Lin',        'Brandon Meyer',          'Jason Price',
         'Nicole Brown']
Length: 2000, dtype: str

In [10]:
df['name'].nunique()

2000

In [11]:
df['name'].value_counts()

name
Allison Hill       1
Brandon Hall       1
Rhonda Smith       1
Gabrielle Davis    1
Valerie Gray       1
                  ..
James Schaefer     1
Diana Lin          1
Brandon Meyer      1
Jason Price        1
Nicole Brown       1
Name: count, Length: 2000, dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates(inplace= True)

In [14]:
df.isnull().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [15]:
df.dropna(inplace= True)  # remove null values permanently

In [16]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [17]:
df.drop(['city'], axis= 1, inplace= True)

In [18]:
df.drop('name',axis=1, inplace=True)

In [19]:
char = df.select_dtypes(include='object')  # all the categorical data will stored in char
num = df.select_dtypes(exclude='object')

In [20]:
char

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2000 rows x 0 columns]

In [21]:
num

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [22]:
char.columns

Index([], dtype='str')

In [23]:
total_df = pd.concat([char,num],axis=1)

In [24]:
total_df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [25]:
total_df.duplicated().sum()

np.int64(0)

In [26]:
total_df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [27]:
# df.to_csv("loan_approval_cleaned.csv",index=False)

In [28]:
df = pd.read_csv(r"Data\clened_loan.csv")

In [29]:
x = total_df.drop(columns='loan_approved')
y = total_df[['loan_approved']]

In [30]:
x

      income  credit_score  loan_amount  years_employed  points
0     113810           389        39698              27    50.0
1      44592           729        15446              28    55.0
2      33278           584        11189              13    45.0
3     127196           344        48823              29    50.0
4      66048           496        47174               4    25.0
...      ...           ...          ...             ...     ...
1995   92163           770        12251              13    85.0
1996   38799           635        48259              17    40.0
1997   41957           763        16752               5    60.0
1998  139022           360        24031              35    55.0
1999   41188           482        31397               6    20.0

[2000 rows x 5 columns]

In [31]:
y

      loan_approved
0             False
1             False
2             False
3             False
4             False
...             ...
1995           True
1996          False
1997           True
1998          False
1999          False

[2000 rows x 1 columns]

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [33]:
x_train.shape, y_train.shape, x_test.shape,  y_test.shape

((1600, 5), (1600, 1), (400, 5), (400, 1))

# SVM(svc)

In [34]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [35]:
print('test score:-',sv.score(x_test,y_test))
print('train score:-',sv.score(x_train,y_train))

test score:- 0.5975
train score:- 0.63

# Dicision Tree Classifior

In [36]:
from sklearn.tree import DecisionTreeClassifier
import joblib
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)
joblib.dump(dt,"dtc.lb")

['dtc.lb']

In [37]:

print('test score:-',dt.score(x_test,y_test))
print('training score:-',dt.score(x_train,y_train))

test score:- 1.0
training score:- 1.0

In [38]:
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

# With parameter classifior

In [39]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dt =DecisionTreeClassifier(criterion='gini', min_samples_split=2, min_samples_leaf=1, random_state=0)
dt.fit(x_train, y_train)

DecisionTreeClassifier(random_state=0)

In [40]:

print('test score:-',dt.score(x_test,y_test))
print('train score:-',dt.score(x_train,y_train))

test score:- 1.0
train score:- 1.0

In [41]:
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': 0,
 'splitter': 'best'}

# Random Forest Classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x, y)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [43]:

print('test score:-',rfc.score(x_test,y_test))
print('train score:-',rfc.score(x_train,y_train))

test score:- 1.0
train score:- 1.0

In [45]:
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [46]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100, min_samples_split=2, min_samples_leaf=1 )
rfc.fit(x_train, y_train)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [47]:

print('test score:-',rfc.score(x_test,y_test))
print('train score:-',rfc.score(x_train,y_train))

test score:- 1.0
train score:- 1.0

# KNN

In [48]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

c:\Users\abc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [49]:

print('test score:-',rfc.score(x_test,y_test))
print('train score:-',rfc.score(x_train,y_train))

test score:- 1.0
train score:- 1.0